# Generated by Django 6.0.1 on 2026-03-02 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfusionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_a', models.CharField(max_length=3)),
                ('letter_b', models.CharField(max_length=3)),
                ('sound_a', models.FileField(blank=True, null=True, upload_to='confusion/audio/')),
                ('sound_b', models.FileField(blank=True, null=True, upload_to='confusion/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='ListenWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='listen/audio/')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Short CVC words'), (2, 'Blends & digraphs'), (3, 'Multi-syllable')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Phoneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_file', models.FileField(upload_to='phonemes/audio/')),
                ('phoneme_text', models.CharField(max_length=10)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Single Letters'), (2, 'Consonant Blends'), (3, 'Digraphs'), (4, 'Vowel Teams')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SightWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('frequency_score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Simple sentences'), (2, 'Short paragraphs'), (3, 'Fill-in-the-blank')], default=1)),
                ('hard_words', models.TextField(blank=True, help_text='Comma-separated')),
                ('fill_blanks', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SyllableWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('syllable_structure', models.JSONField()),
                ('difficulty_level', models.IntegerField(choices=[(1, '2 syllables'), (2, '3 syllables'), (3, '4+ syllables')], default=1)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='syllables/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='words/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='words/audio/')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Basic (3 letters)'), (2, 'Medium (4–5 letters)'), (3, 'Advanced (digraphs/blends)'), (4, 'Expert (long words)')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConfusionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_letter', models.CharField(max_length=3)),
                ('selected', models.CharField(max_length=3)),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confusion_attempts', to=settings.AUTH_USER_MODEL)),
                ('confusion_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.confusionset')),
            ],
        ),
        migrations.CreateModel(
            name='ListenAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_answer', models.CharField(max_length=60)),
                ('is_correct', models.BooleanField()),
                ('wrong_positions', models.JSONField(blank=True, default=list)),
                ('response_time', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_attempts', to=settings.AUTH_USER_MODEL)),
                ('listen_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.listenword')),
            ],
        ),
        migrations.CreateModel(
            name='PhonemeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_option', models.CharField(max_length=5)),
                ('is_correct', models.BooleanField(default=False)),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='games.phoneme')),
            ],
        ),
        migrations.CreateModel(
            name='PhonemeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField(help_text='seconds')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.phoneme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_attempts', to=settings.AUTH_USER_MODEL)),
                ('selected_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.phonemeoption')),
            ],
        ),
        migrations.CreateModel(
            name='SightWordAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sight_word_attempts', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sightword')),
            ],
        ),
        migrations.CreateModel(
            name='StoryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('fill_answers', models.JSONField(blank=True, default=dict)),
                ('time_spent', models.FloatField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyllableAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_splits', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllable_attempts', to=settings.AUTH_USER_MODEL)),
                ('syllable_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.syllableword')),
            ],
        ),
        migrations.CreateModel(
            name='WordBuildAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_order', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_build_attempts', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=3)),
                ('position', models.PositiveIntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='games.word')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UserErrorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('bd_confusion', 'b/d Confusion'), ('pq_confusion', 'p/q Confusion'), ('vowel_substitution', 'Vowel Substitution'), ('blending_failure', 'Blending Failure'), ('syllable_segmentation', 'Syllable Segmentation Error'), ('sight_word_miss', 'Sight Word Miss'), ('phoneme_miss', 'Phoneme Miss')], max_length=40)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-frequency'],
                'unique_together': {('user', 'error_type')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('sound_match', 'Sound–Letter Match'), ('word_builder', 'Word Builder'), ('sight_word', 'Sight Word Speed Tap'), ('confusion', 'Confusing Letter Fix'), ('syllable', 'Syllable Breaker'), ('listen_type', 'Listening & Type'), ('story_builder', 'Story Builder')], max_length=30)),
                ('level', models.PositiveIntegerField(default=1)),
                ('accuracy', models.FloatField(default=0.0)),
                ('average_time', models.FloatField(default=0.0)),
                ('sessions_at_level', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_type')},
            },
        ),
        migrations.CreateModel(
            name='UserSightWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sight_word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.sightword')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
