# Generated by Django 6.0.1 on 2026-03-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_passwordresettoken_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountstatus',
            options={'verbose_name_plural': 'Account Statuses'},
        ),
        migrations.AlterModelOptions(
            name='loginactivity',
            options={'ordering': ['-login_time'], 'verbose_name_plural': 'Login Activities'},
        ),
    ]
