# Generated by Django 6.0.1 on 2026-02-25 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='tts_uploads/')),
                ('extracted_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tts_audio/')),
                ('hard_words', models.JSONField(blank=True, default=list)),
                ('syllables', models.JSONField(blank=True, default=dict)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
